# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: Le Club
    submenu:
      - name : Présentation
        link: /le-club
      - name : Les entrainements
        link: /le-club
      - name : Actualités
        link: /

  - name: Inscription
    link: /inscription
  - name: Le Volley
    submenu:
      - name: Les Règles
        link: /volley/regles
      - name: L'équipe de France
        link: /volley/team-france
      - name: Exrecices
        link: /volley/team-france
  - name: Contact
    link: /contact

    
