# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: Le Club
    link: /le-club
  - name: Inscription
    link: /inscription
  - name: Contact
    link: /contact

    
